### PR TITLE
Bump MSRV to 1.65

### PR DESCRIPTION
**Pull request by uint**

### CODE REVIEW

**Comment by frol** [comment]
@uint I would avoid bumping MSRV just because some other dependency bumped it. I would only bump it if minimal dependencies require it.

**Comment by uint** [comment]
@frol Right now if someone uses `1.64` and tries to set up a new project using `near-account-id`, they'll get an almost guaranteed compilation failure. Could be confusing given our promise that the thing supports `1.64` unless we further clarify.

**Comment by frol** [comment]
Someone creating a new project will then most probably just update their toolchain to the latest stable and keep going. While old users of near-account-id will be forced to update their MSRV.

**Comment by uint** [comment]
@frol Fair. If you'd like to change it back to `1.64`, I'm happy for it.

**Pull request merged**
